### PR TITLE
Enabling parallelism with std::thread

### PR DESCRIPTION
**Pull request by fengwang**
In my side (Linux 5.2.9 with a Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz), this implementation is about 6 time faster than openmp implementation.

### CODE REVIEW

**Comment by tjof2** [comment]
@fengwang  can you confirm it produces the same output? e.g. to a tolerance, the output matrices are identical?

**Comment by fengwang** [comment]
@tjof2 Yes.

I tested the compiled executables with the STEM image experimentalsequence-NP.tif in folder examples, using identical param.svt as configuration file. The produced files share same md5 hash.

**Comment by fengwang** [comment]
@tjof2 I have pushed the configuration. It is at https://github.com/fengwang/pgure-svt/blob/master/examples/param_se.svt

**Comment by tjof2** [comment]
@fengwang  thanks very much! Looks good to me otherwise

**Pull request merged**
